#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Digital Sentinel v11.1 - Autonomous Report Composer
Author: Mhamad Mahdy (Commander "Themoralhack")
Purpose: Auto-compose markdown + Discord-ready report summary after each scan cycle.
"""

import os
import json
import datetime
import statistics

REPORT_DIR = "data/reports"
LOG_DIR = "data/logs"
OUTPUT_FILE = os.path.join(REPORT_DIR, "Eternal_Summary_Report.md")
DISCORD_SUMMARY = os.path.join(REPORT_DIR, "Eternal_Discord_Embed.json")


def load_reports():
    """Load all JSON reports from previous cycles."""
    reports = []
    if not os.path.exists(REPORT_DIR):
        return reports

    for file in os.listdir(REPORT_DIR):
        if file.endswith(".json"):
            path = os.path.join(REPORT_DIR, file)
            try:
                with open(path, "r", encoding="utf-8") as f:
                    reports.append(json.load(f))
            except Exception as e:
                print(f"⚠️ Skipping {file}: {e}")
    return reports


def analyze_reports(reports):
    """Extract summarized vulnerability statistics."""
    total_targets = 0
    total_findings = 0
    severity_count = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}

    for r in reports:
        total_targets += len(r.get("targets", []))
        findings = r.get("findings", [])
        total_findings += len(findings)

        for f in findings:
            sev = f.get("severity", "").upper()
            if sev in severity_count:
                severity_count[sev] += 1

    return {
        "total_reports": len(reports),
        "total_targets": total_targets,
        "total_findings": total_findings,
        "severity_breakdown": severity_count
    }


def generate_markdown(summary):
    """Generate Markdown summary report."""
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    md = [
        f"# 🧠 Digital Sentinel v11.1 – Autonomous Summary Report",
        f"**Generated at:** {now}",
        "---",
        f"### 📊 Scan Summary",
        f"- Reports analyzed: **{summary['total_reports']}**",
        f"- Total targets scanned: **{summary['total_targets']}**",
        f"- Total findings: **{summary['total_findings']}**",
        "",
        "### 🔥 Severity Breakdown",
        "| Severity | Count |",
        "|-----------|--------|",
    ]

    for sev, count in summary["severity_breakdown"].items():
        emoji = {"CRITICAL": "🟥", "HIGH": "🟧", "MEDIUM": "🟨", "LOW": "🟩"}.get(sev, "⚪")
        md.append(f"| {emoji} {sev} | {count} |")

    md += [
        "",
        "---",
        f"🧠 *End of cycle summary automatically generated by Digital Sentinel.*",
    ]

    return "\n".join(md)


def generate_discord_embed(summary):
    """Generate Discord JSON payload for embedding."""
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    embed = {
        "username": "Digital Sentinel",
        "avatar_url": "https://i.imgur.com/z5VIvQv.png",
        "embeds": [
            {
                "title": "🧠 Digital Sentinel v11.1 – Summary Report",
                "description": f"**Reports:** {summary['total_reports']}\n"
                               f"**Targets:** {summary['total_targets']}\n"
                               f"**Findings:** {summary['total_findings']}",
                "color": 0x7289DA,
                "fields": [
                    {"name": "🟥 Critical", "value": str(summary['severity_breakdown']['CRITICAL']), "inline": True},
                    {"name": "🟧 High", "value": str(summary['severity_breakdown']['HIGH']), "inline": True},
                    {"name": "🟨 Medium", "value": str(summary['severity_breakdown']['MEDIUM']), "inline": True},
                    {"name": "🟩 Low", "value": str(summary['severity_breakdown']['LOW']), "inline": True}
                ],
                "footer": {"text": f"Generated at {now}"}
            }
        ]
    }

    with open(DISCORD_SUMMARY, "w", encoding="utf-8") as f:
        json.dump(embed, f, indent=4)

    return embed


def main():
    print("🧠 Composing Autonomous Summary Report...")
    reports = load_reports()
    if not reports:
        print("⚠️ No reports found to summarize.")
        return

    summary = analyze_reports(reports)
    markdown = generate_markdown(summary)
    embed = generate_discord_embed(summary)

    # Write Markdown file
    os.makedirs(REPORT_DIR, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(markdown)

    print(f"✅ Report composed successfully: {OUTPUT_FILE}")
    print(f"✅ Discord Embed saved: {DISCORD_SUMMARY}")


if __name__ == "__main__":
    main()
