import os, json, random
from datetime import datetime

MEMORY_FILE = "data/sentinel_memory.json"
CHANGELOG = "data/genesis_changelog.json"
SRC_PATH = "src/"

def load_json(path, default=None):
    try:
        return json.load(open(path))
    except Exception:
        return default if default else {}

def save_json(path, data):
    json.dump(data, open(path, "w"), indent=2)

def suggest_new_module():
    """AI generates name for next evolution module."""
    candidates = [
        "cognitive_optimizer", "neural_feedback",
        "adaptive_scheduler", "contextual_reasoner",
        "meta_defense_unit", "behavioral_mapper"
    ]
    return random.choice(candidates) + ".py"

def analyze_performance(mem):
    """Simple adaptive feedback: if failures > 3, trigger redesign."""
    if mem.get("failures", 0) >= 3:
        print("⚠️ High failure rate detected – initiating self-evolution...")
        return True
    return False

def create_new_module(filename):
    """Autonomously generates new Python module."""
    code = f'''"""
Auto-generated by Genesis Engine v10.0
Created: {datetime.utcnow().isoformat()}
Purpose: Experimental sub-module for autonomous intelligence.
"""
def run():
    print("[🧬 Genesis] {filename} active — learning module initialized.")
'''
    path = os.path.join(SRC_PATH, filename)
    with open(path, "w") as f:
        f.write(code)
    print(f"🧠 Genesis created new module → {filename}")
    return filename

def record_evolution(module):
    changelog = load_json(CHANGELOG, {"history": []})
    changelog["history"].append({
        "module": module,
        "timestamp": datetime.utcnow().isoformat()
    })
    save_json(CHANGELOG, changelog)

def run_genesis_cycle():
    """Genesis Engine — self-evolving intelligence."""
    mem = load_json(MEMORY_FILE, {})
    if analyze_performance(mem):
        new_module = suggest_new_module()
        create_new_module(new_module)
        record_evolution(new_module)
        print(f"[🧬 Genesis] Self-evolution complete → {new_module}")
    else:
        print("[🧩 Stable performance — no evolution required.]")
